//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_DESKTOP.WebServReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServReference.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetData(string query, string TableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string query, string TableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByStoreProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataByStoreProcedure(string StoreProcedureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByStoreProcedure", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataByStoreProcedureAsync(string StoreProcedureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByStoreProcedureWithParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet GetDataByStoreProcedureWithParameters(string StoreProcedureName, string[] ParametersName, object[] ParametersValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByStoreProcedureWithParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataByStoreProcedureWithParametersAsync(string StoreProcedureName, string[] ParametersName, object[] ParametersValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : APP_DESKTOP.WebServReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<APP_DESKTOP.WebServReference.WebService1Soap>, APP_DESKTOP.WebServReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetData(string query, string TableName) {
            return base.Channel.GetData(query, TableName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string query, string TableName) {
            return base.Channel.GetDataAsync(query, TableName);
        }
        
        public System.Data.DataSet GetDataByStoreProcedure(string StoreProcedureName) {
            return base.Channel.GetDataByStoreProcedure(StoreProcedureName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataByStoreProcedureAsync(string StoreProcedureName) {
            return base.Channel.GetDataByStoreProcedureAsync(StoreProcedureName);
        }
        
        public System.Data.DataSet GetDataByStoreProcedureWithParameters(string StoreProcedureName, string[] ParametersName, object[] ParametersValue) {
            return base.Channel.GetDataByStoreProcedureWithParameters(StoreProcedureName, ParametersName, ParametersValue);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataByStoreProcedureWithParametersAsync(string StoreProcedureName, string[] ParametersName, object[] ParametersValue) {
            return base.Channel.GetDataByStoreProcedureWithParametersAsync(StoreProcedureName, ParametersName, ParametersValue);
        }
    }
}
